CREATE TABLE PACIENTE (
  ID_PACIENTE INTEGER PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  APELLIDO_PATERNO VARCHAR2(50),
  APELLIDO_MATERNO VARCHAR2(50),
  FECHA_DE_NACIMIENTO DATE,
  SEXO VARCHAR2(20),
  TIPO_DE_SANGRE VARCHAR2(10),
  TELEFONO NUMBER(20),
  DIRECCION VARCHAR2(30),
  EMAIL VARCHAR2(50),
  FECHA_REGISTRO DATE
);
 SELECT * FROM PACIENTE;

CREATE TABLE DOCTOR (
  ID_DOCTOR INTEGER PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  APELLIDO_PATERNO VARCHAR2(60),
  APELLIDO_MATERNO VARCHAR2(60),
  ESPECIALIDAD VARCHAR2(50),
  CEDULA_PROFECIONAL NUMBER,
  TELEFONO NUMBER,
  EMAIL VARCHAR2(50),
  FECHA_CONTRATACION DATE
);

 SELECT * FROM DOCTOR;
 
CREATE TABLE CITA_MEDICA (
  ID_CITA INTEGER PRIMARY KEY,
  FECHA DATE,
  HORA TIMESTAMP,
  MOTIVO VARCHAR2(500),
  ID_PACIENTE INTEGER,
  ID_DOCTOR INTEGER,
  OBSERVACIONES VARCHAR2(2000),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
  FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR)
);

 SELECT * FROM CITA_MEDICA;
 
CREATE TABLE CONSULTA (
  ID_CONSULTA INTEGER PRIMARY KEY,
  ID_CITA INTEGER,
  DIAGNOSTICO VARCHAR2(1600),
  TRATAMIENTO VARCHAR2(2000),
  RECETA VARCHAR2(1000),
  FECHA DATE,
  FOREIGN KEY (ID_CITA) REFERENCES CITA_MEDICA(ID_CITA)
);

 SELECT * FROM CONSULTA;
 
CREATE TABLE MEDICAMENTO (
  ID_MEDICAMENTO INTEGER PRIMARY KEY,
  NOMBRE VARCHAR2(300),
  DESCRIPCION VARCHAR(500),
  LABORATORIO VARCHAR2(300),
  PRESENTACION VARCHAR2(200),
  STOCK_ACTUAL NUMBER(38)
);

 SELECT * FROM MEDICAMENTO;
 
CREATE TABLE PRESCRIPCION_MEDICA (
  ID_PRESCRIPCION_MEDICA NUMBER(30) PRIMARY KEY,
  ID_CONSULTA NUMBER(30),
  ID_MEDICAMENTO NUMBER(30),
  DOSIS VARCHAR2(200),
  FRECUENCIA VARCHAR(300),
  DURACION_EN_DIAS DATE,
  FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA),
  FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);

 SELECT * FROM PRESCRIPCION_MEDICA;
 
 
CREATE TABLE HABITACION (
  ID_HABITACION NUMBER(30) PRIMARY KEY,
  NUMERO_DE_HABITACION NUMBER(30),
  TIPO_DE_HABITACION VARCHAR2(100)
);


 SELECT * FROM HABITACION;
 
CREATE TABLE PISO (
  ID_PISO NUMBER(30) PRIMARY KEY,
  ESTATUS VARCHAR2(100)
);


 SELECT * FROM PISO;
 
CREATE TABLE CIRUGIA (
  ID_CIRUGIA NUMBER(30) PRIMARY KEY,
  TIPO_DE_CIRUGIA VARCHAR2(800),
  FECHA DATE,
  ID_PACIENTE NUMBER(30),
  ID_DOCTOR NUMBER(10),
  DURACION_EN_MINUTOS TIMESTAMP,
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
  FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR)
);
 
 
  SELECT * FROM CIRUGIA;
  
CREATE TABLE NOTAS_MEDICAS (
  ID_FACTURAS NUMBER(30) PRIMARY KEY,
  FACTURAS VARCHAR2(200),
  FECHA_FACTURA DATE,
  ID_PACIENTE NUMBER(30),
  MONTO_TOTAL FLOAT,
  METODO_DE_PAGO VARCHAR2(100),
  ESTATUS_DE_PAGO VARCHAR2(100),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);


 SELECT * FROM NOTAS_MEDICAS;
 
 
CREATE TABLE PROV (
  ID_PROV NUMBER(30) PRIMARY KEY,
  NOMBRE_EMPRESA VARCHAR2(200),
  TELEFONO NUMBER(30),
  DIRECCION VARCHAR2(200),
  EMAIL VARCHAR2(200)
);

 SELECT * FROM PROV;
 
SELECT *FROM PACIENTE;
SELECT * FROM DOCTOR;
SELECT *FROM CITA_MEDICA;
SELECT * FROM CONSULTA;
SELECT *FROM MEDICAMENTO;
SELECT * FROM PRESCRIPCION_MEDICA;
SELECT * FROM HABITACION;
SELECT * FROM PISO;
SELECT * FROM CIRUGIA;
SELECT * FROM NOTAS_MEDICAS;
SELECT * FROM PROV;



